### ISSUE TITLE
Implementación de lo planeado a codigo

### ISSUE THREAD

**Issue by Tyrone-J** [SebastianOsorio20/Trabajo-Parcial#10]
En esta parte nos reunimos para codear a base de lo coordinado eh implementamos cada uno un método abarcando diferentes areas.

**Comment by SebastianOsorio20** [comment]
Se logro implementar los lambdas y templates al proyecto

**Comment by Tyrone-J** [comment]
asi es

**Comment by MarlonLLaguento** [comment]
Logramos implementar exitosamente las estructuras de datos.
