### ISSUE TITLE
Implementación de estructura de datos

### ISSUE THREAD

**Issue by MarlonLLaguento** [SebastianOsorio20/Trabajo-Parcial#12]
Implementación de las listas, estructuras y arreglos, para el manejo de archivos, registro de usuarios y para la edición de los archivos.

**Comment by MarlonLLaguento** [comment]
Hicimos el uso de listas para el registro de nuevos usuarios y su respectiva búsqueda. Así logramos, el ingreso de internautas en tiempos cortos y con un menor coste computacional.

**Comment by SebastianOsorio20** [comment]
Se implemento listas simples con templates para la clase usuario

**Comment by Tyrone-J** [comment]
XD

**Comment by Tyrone-J** [comment]
creamos nuestro propio vector que representaría un tipo de dato Array siendo este array utilizado por un struct que creamos en el código.
