### ISSUE TITLE
Realización del Informe

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo-Parcial#13]
Nos reuniremos para desarrollar el informe pedido

**Comment by Tyrone-J** [comment]
Como lo indica mi compañero Sebastian Osorio, en este punto todo el grupo realizo una reunion grupal para culminar con el Informe. Tengo que darle crédito a mi Compañero Marlon LLaguento ya que el fue el que realizo mayores aportes en esta sección. Pero igualmente en el ultimo día de entrega nos reunimos  para proceder a evaluar el informe corrigiendo diversos puntos y quedando finalmente conformes con el resultado de nuestro trabajo.

**Comment by MarlonLLaguento** [comment]
Con el proyecto terminado, realizamos el informe donde se encuentra tanto nuestro diagrama de clases y la explicación del uso de las estructuras.

**Comment by SebastianOsorio20** [comment]
Se realizo la notación big 0 de algunas funciones
