### ISSUE TITLE
Definición del Alcance del Proyecto

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo-Parcial#7]

**Comment by MarlonLLaguento** [comment]
Reunión de equipo para la planificación del funcionamiento del programa.

**Comment by Tyrone-J** [comment]
en efecto mis estimados, en este punto logramos cumplir todas las funcionalidades que nos presentaba el contenido de la rubrica, dándonos una reflexión sobre nuestro trabajo conociendo a mas detalle el funcionamiento de los diversos tipos de estructura de datos que utilizamos en la realización de nuestro proyecto.

**Comment by SebastianOsorio20** [comment]
Todos quedamos en una idea para la realización del proyecto
