### ISSUE TITLE
Testeo del programa

### ISSUE THREAD

**Issue by Tyrone-J** [SebastianOsorio20/Trabajo-Parcial#8]
En esta sección se realizo Varios testeos para asegurar que todo corriera correctamente, Esto se solía hacer después de cada sección de codeo que teníamos para corroborar de que nuestros códigos estén bien.

**Comment by MarlonLLaguento** [comment]
Se realizaron multiples pruebas para verificar el correcto funcionamiento de nuestro programa. Como por ejemplo, registrar usuarios, crear sus carpetas, crear archivos y editarlos. Las pruebas se pasaron satisfactoriamente.

**Comment by SebastianOsorio20** [comment]
Se testeo el programa con la finalidad de encontrar algún bug restante
