### ISSUE TITLE
Creación del Menú

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo-Parcial#9]

**Comment by Tyrone-J** [comment]
confirmo

**Comment by MarlonLLaguento** [comment]
Consideramos todas las opciones para que el usuario pueda navegar de manera correcta y sin posibles equivocaciones a la hora de seleccionar las opciones.

**Comment by Tyrone-J** [comment]
El menu quedo piola 😎

**Comment by SebastianOsorio20** [comment]
Quedamos en implementar un menú dinámico para un uso de fácil acceso
